# Generated by Django 4.2 on 2023-04-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=500)),
                ('address', models.CharField(max_length=500)),
                ('Qualification', models.CharField(max_length=500)),
                ('Qualification_name', models.CharField(max_length=500)),
                ('Project_Name', models.CharField(max_length=500)),
                ('Title', models.CharField(max_length=500)),
                ('Description', models.TextField()),
                ('from_date', models.DateTimeField(auto_now=True)),
                ('to_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
